(function(){

"use strict";

var get_hiragana = function(txt){
  var ret = {};
  for(var idx=0; idx<roma2hiragana_tbl_len; idx++){
    var item = roma2hiragana_tbl[idx];
    var match = txt.match(item.replace);
    if(match){
      ret.match = true;
      ret.txt = txt.replace(item.replace, item.with);
      ret.hiragana = item.hiragana;
      break;
    }
  }
  return ret;
};

var conv = function(in_txt){
  var ret = {
    text:'',
    complete:false
  };
  var txt = in_txt;
  while(txt){
    var hiragana_item = get_hiragana(txt);
    if(hiragana_item.match){
      ret.text = ret.text + hiragana_item.hiragana;
      ret.complete = true;
      txt = hiragana_item.txt;
    }else{
      var chr = txt.substr(0, 1);
      var dbl = hankaku2zenkaku[chr];
      if(dbl){
        ret.text = ret.text + dbl;
      }else{
        ret.text = ret.text + chr;
      }
      ret.complete = false;
      txt = txt.substring(1)
    }
  }
  return ret;
};

var chr_convtbl = {
  hankaku2zenkaku:{
    " ":"　",
    "!":"！",
    "\"":"”",
    "#":"＃",
    "$":"＄",
    "%":"％",
    "&":"＆",
    "'":"’",
    "(":"（",
    ")":"）",
    "*":"＊",
    "+":"＋",
    ",":"，",
    "-":"－",
    ".":"．",
    "/":"／",
    "0":"０",
    "1":"１",
    "2":"２",
    "3":"３",
    "4":"４",
    "5":"５",
    "6":"６",
    "7":"７",
    "8":"８",
    "9":"９",
    ":":"：",
    ";":"；",
    "<":"＜",
    "=":"＝",
    ">":"＞",
    "?":"？",
    "@":"＠",
    "A":"Ａ",
    "B":"Ｂ",
    "C":"Ｃ",
    "D":"Ｄ",
    "E":"Ｅ",
    "F":"Ｆ",
    "G":"Ｇ",
    "H":"Ｈ",
    "I":"Ｉ",
    "J":"Ｊ",
    "K":"Ｋ",
    "L":"Ｌ",
    "M":"Ｍ",
    "N":"Ｎ",
    "O":"Ｏ",
    "P":"Ｐ",
    "Q":"Ｑ",
    "R":"Ｒ",
    "S":"Ｓ",
    "T":"Ｔ",
    "U":"Ｕ",
    "V":"Ｖ",
    "W":"Ｗ",
    "X":"Ｘ",
    "Y":"Ｙ",
    "Z":"Ｚ",
    "[":"［",
    "\\":"￥",
    "]":"］",
    "^":"＾",
    "_":"＿",
    "`":"‘",
    "a":"ａ",
    "b":"ｂ",
    "c":"ｃ",
    "d":"ｄ",
    "e":"ｅ",
    "f":"ｆ",
    "g":"ｇ",
    "h":"ｈ",
    "i":"ｉ",
    "j":"ｊ",
    "k":"ｋ",
    "l":"ｌ",
    "m":"ｍ",
    "n":"ｎ",
    "o":"ｏ",
    "p":"ｐ",
    "q":"ｑ",
    "r":"ｒ",
    "s":"ｓ",
    "t":"ｔ",
    "u":"ｕ",
    "v":"ｖ",
    "w":"ｗ",
    "x":"ｘ",
    "y":"ｙ",
    "z":"ｚ",
    "{":"｛",
    "|":"｜",
    "}":"｝",
    "~":"～"
  },
  hiragana2katakana:{
    "いぇ":{"zenkaku":"イェ","hankaku":"ｲｪ"},
    "ヴぁ":{"zenkaku":"ヴァ","hankaku":"ｳﾞｧ"},
    "うぃ":{"zenkaku":"ウィ","hankaku":"ｳｨ"},
    "ヴぃ":{"zenkaku":"ヴィ","hankaku":"ｳﾞｨ"},
    "うぇ":{"zenkaku":"ウェ","hankaku":"ｳｪ"},
    "ヴぇ":{"zenkaku":"ヴェ","hankaku":"ｳﾞｪ"},
    "うぉ":{"zenkaku":"ウォ","hankaku":"ｳｫ"},
    "ヴぉ":{"zenkaku":"ヴォ","hankaku":"ｳﾞｫ"},
    "ヴゅ":{"zenkaku":"ヴュ","hankaku":"ｳﾞｭ"},
    "きゃ":{"zenkaku":"キャ","hankaku":"ｷｬ"},
    "ぎゃ":{"zenkaku":"ギャ","hankaku":"ｷﾞｬ"},
    "きゅ":{"zenkaku":"キュ","hankaku":"ｷｭ"},
    "ぎゅ":{"zenkaku":"ギュ","hankaku":"ｷﾞｭ"},
    "きょ":{"zenkaku":"キョ","hankaku":"ｷｮ"},
    "ぎょ":{"zenkaku":"ギョ","hankaku":"ｷﾞｮ"},
    "くぁ":{"zenkaku":"クァ","hankaku":"ｸｧ"},
    "ぐぁ":{"zenkaku":"グァ","hankaku":"ｸﾞｧ"},
    "くぃ":{"zenkaku":"クィ","hankaku":"ｸｨ"},
    "くぇ":{"zenkaku":"クェ","hankaku":"ｸｪ"},
    "くぉ":{"zenkaku":"クォ","hankaku":"ｸｫ"},
    "しぇ":{"zenkaku":"シェ","hankaku":"ｼｪ"},
    "じぇ":{"zenkaku":"ジェ","hankaku":"ｼﾞｪ"},
    "しゃ":{"zenkaku":"シャ","hankaku":"ｼｬ"},
    "じゃ":{"zenkaku":"ジャ","hankaku":"ｼﾞｬ"},
    "しゅ":{"zenkaku":"シュ","hankaku":"ｼｭ"},
    "じゅ":{"zenkaku":"ジュ","hankaku":"ｼﾞｭ"},
    "しょ":{"zenkaku":"ショ","hankaku":"ｼｮ"},
    "じょ":{"zenkaku":"ジョ","hankaku":"ｼﾞｮ"},
    "ちぇ":{"zenkaku":"チェ","hankaku":"ﾁｪ"},
    "ちゃ":{"zenkaku":"チャ","hankaku":"ﾁｬ"},
    "ぢゃ":{"zenkaku":"ヂャ","hankaku":"ﾁﾞｬ"},
    "ちゅ":{"zenkaku":"チュ","hankaku":"ﾁｭ"},
    "ぢゅ":{"zenkaku":"ヂュ","hankaku":"ﾁﾞｭ"},
    "ちょ":{"zenkaku":"チョ","hankaku":"ﾁｮ"},
    "ぢょ":{"zenkaku":"ヂョ","hankaku":"ﾁﾞｮ"},
    "つぁ":{"zenkaku":"ツァ","hankaku":"ﾂｧ"},
    "つぃ":{"zenkaku":"ツィ","hankaku":"ﾂｨ"},
    "つぇ":{"zenkaku":"ツェ","hankaku":"ﾂｪ"},
    "つぉ":{"zenkaku":"ツォ","hankaku":"ﾂｫ"},
    "てぃ":{"zenkaku":"ティ","hankaku":"ﾃｨ"},
    "でぃ":{"zenkaku":"ディ","hankaku":"ﾃﾞｨ"},
    "てゅ":{"zenkaku":"テュ","hankaku":"ﾃｭ"},
    "でゅ":{"zenkaku":"デュ","hankaku":"ﾃﾞｭ"},
    "とぅ":{"zenkaku":"トゥ","hankaku":"ﾄｩ"},
    "どぅ":{"zenkaku":"ドゥ","hankaku":"ﾄﾞｩ"},
    "にゃ":{"zenkaku":"ニャ","hankaku":"ﾆｬ"},
    "にゅ":{"zenkaku":"ニュ","hankaku":"ﾆｭ"},
    "にょ":{"zenkaku":"ニョ","hankaku":"ﾆｮ"},
    "ひゃ":{"zenkaku":"ヒャ","hankaku":"ﾋｬ"},
    "びゃ":{"zenkaku":"ビャ","hankaku":"ﾋﾞｬ"},
    "ぴゃ":{"zenkaku":"ピャ","hankaku":"ﾋﾟｬ"},
    "ひゅ":{"zenkaku":"ヒュ","hankaku":"ﾋｭ"},
    "びゅ":{"zenkaku":"ビュ","hankaku":"ﾋﾞｭ"},
    "ぴゅ":{"zenkaku":"ピュ","hankaku":"ﾋﾟｭ"},
    "ひょ":{"zenkaku":"ヒョ","hankaku":"ﾋｮ"},
    "びょ":{"zenkaku":"ビョ","hankaku":"ﾋﾞｮ"},
    "ぴょ":{"zenkaku":"ピョ","hankaku":"ﾋﾟｮ"},
    "ふぁ":{"zenkaku":"ファ","hankaku":"ﾌｧ"},
    "ふぃ":{"zenkaku":"フィ","hankaku":"ﾌｨ"},
    "ふぇ":{"zenkaku":"フェ","hankaku":"ﾌｪ"},
    "ふぉ":{"zenkaku":"フォ","hankaku":"ﾌｫ"},
    "ふゅ":{"zenkaku":"フュ","hankaku":"ﾌｭ"},
    "みゃ":{"zenkaku":"ミャ","hankaku":"ﾐｬ"},
    "みゅ":{"zenkaku":"ミュ","hankaku":"ﾐｭ"},
    "みょ":{"zenkaku":"ミョ","hankaku":"ﾐｮ"},
    "りゃ":{"zenkaku":"リャ","hankaku":"ﾘｬ"},
    "りゅ":{"zenkaku":"リュ","hankaku":"ﾘｭ"},
    "りょ":{"zenkaku":"リョ","hankaku":"ﾘｮ"},
    "ぁ":{"zenkaku":"ァ","hankaku":"ｧ"},
    "あ":{"zenkaku":"ア","hankaku":"ｱ"},
    "ぃ":{"zenkaku":"ィ","hankaku":"ｨ"},
    "い":{"zenkaku":"イ","hankaku":"ｲ"},
    "ぅ":{"zenkaku":"ゥ","hankaku":"ｩ"},
    "う":{"zenkaku":"ウ","hankaku":"ｳ"},
    "ヴ":{"zenkaku":"ヴ","hankaku":"ｳﾞ"},
    "ぇ":{"zenkaku":"ェ","hankaku":"ｪ"},
    "え":{"zenkaku":"エ","hankaku":"ｴ"},
    "ぉ":{"zenkaku":"ォ","hankaku":"ｫ"},
    "お":{"zenkaku":"オ","hankaku":"ｵ"},
    "ヵ":{"zenkaku":"カ","hankaku":"ｶ"},
    "か":{"zenkaku":"カ","hankaku":"ｶ"},
    "が":{"zenkaku":"ガ","hankaku":"ｶﾞ"},
    "き":{"zenkaku":"キ","hankaku":"ｷ"},
    "ぎ":{"zenkaku":"ギ","hankaku":"ｷﾞ"},
    "く":{"zenkaku":"ク","hankaku":"ｸ"},
    "ぐ":{"zenkaku":"グ","hankaku":"ｸﾞ"},
    "ヶ":{"zenkaku":"ガ","hankaku":"ｶﾞ"},
    "け":{"zenkaku":"ケ","hankaku":"ｹ"},
    "げ":{"zenkaku":"ゲ","hankaku":"ｹﾞ"},
    "こ":{"zenkaku":"コ","hankaku":"ｺ"},
    "ご":{"zenkaku":"ゴ","hankaku":"ｺﾞ"},
    "さ":{"zenkaku":"サ","hankaku":"ｻ"},
    "ざ":{"zenkaku":"ザ","hankaku":"ｻﾞ"},
    "し":{"zenkaku":"シ","hankaku":"ｼ"},
    "じ":{"zenkaku":"ジ","hankaku":"ｼﾞ"},
    "す":{"zenkaku":"ス","hankaku":"ｽ"},
    "ず":{"zenkaku":"ズ","hankaku":"ｽﾞ"},
    "せ":{"zenkaku":"セ","hankaku":"ｾ"},
    "ぜ":{"zenkaku":"ゼ","hankaku":"ｾﾞ"},
    "そ":{"zenkaku":"ソ","hankaku":"ｿ"},
    "ぞ":{"zenkaku":"ゾ","hankaku":"ｿﾞ"},
    "た":{"zenkaku":"タ","hankaku":"ﾀ"},
    "だ":{"zenkaku":"ダ","hankaku":"ﾀﾞ"},
    "ち":{"zenkaku":"チ","hankaku":"ﾁ"},
    "ぢ":{"zenkaku":"ヂ","hankaku":"ﾁﾞ"},
    "っ":{"zenkaku":"ッ","hankaku":"ｯ"},
    "つ":{"zenkaku":"ツ","hankaku":"ﾂ"},
    "づ":{"zenkaku":"ヅ","hankaku":"ﾂﾞ"},
    "て":{"zenkaku":"テ","hankaku":"ﾃ"},
    "で":{"zenkaku":"デ","hankaku":"ﾃﾞ"},
    "と":{"zenkaku":"ト","hankaku":"ﾄ"},
    "ど":{"zenkaku":"ド","hankaku":"ﾄﾞ"},
    "な":{"zenkaku":"ナ","hankaku":"ﾅ"},
    "に":{"zenkaku":"ニ","hankaku":"ﾆ"},
    "ぬ":{"zenkaku":"ヌ","hankaku":"ﾇ"},
    "ね":{"zenkaku":"ネ","hankaku":"ﾈ"},
    "の":{"zenkaku":"ノ","hankaku":"ﾉ"},
    "は":{"zenkaku":"ハ","hankaku":"ﾊ"},
    "ば":{"zenkaku":"バ","hankaku":"ﾊﾞ"},
    "ぱ":{"zenkaku":"パ","hankaku":"ﾊﾟ"},
    "ひ":{"zenkaku":"ヒ","hankaku":"ﾋ"},
    "び":{"zenkaku":"ビ","hankaku":"ﾋﾞ"},
    "ぴ":{"zenkaku":"ピ","hankaku":"ﾋﾟ"},
    "ふ":{"zenkaku":"フ","hankaku":"ﾌ"},
    "ぶ":{"zenkaku":"ブ","hankaku":"ﾌﾞ"},
    "ぷ":{"zenkaku":"プ","hankaku":"ﾌﾟ"},
    "へ":{"zenkaku":"ヘ","hankaku":"ﾍ"},
    "べ":{"zenkaku":"ベ","hankaku":"ﾍﾞ"},
    "ぺ":{"zenkaku":"ペ","hankaku":"ﾍﾟ"},
    "ほ":{"zenkaku":"ホ","hankaku":"ﾎ"},
    "ぼ":{"zenkaku":"ボ","hankaku":"ﾎﾞ"},
    "ぽ":{"zenkaku":"ポ","hankaku":"ﾎﾟ"},
    "ま":{"zenkaku":"マ","hankaku":"ﾏ"},
    "み":{"zenkaku":"ミ","hankaku":"ﾐ"},
    "む":{"zenkaku":"ム","hankaku":"ﾑ"},
    "め":{"zenkaku":"メ","hankaku":"ﾒ"},
    "も":{"zenkaku":"モ","hankaku":"ﾓ"},
    "ゃ":{"zenkaku":"ャ","hankaku":"ｬ"},
    "や":{"zenkaku":"ヤ","hankaku":"ﾔ"},
    "ゅ":{"zenkaku":"ュ","hankaku":"ｭ"},
    "ゆ":{"zenkaku":"ユ","hankaku":"ﾕ"},
    "ょ":{"zenkaku":"ョ","hankaku":"ｮ"},
    "よ":{"zenkaku":"ヨ","hankaku":"ﾖ"},
    "ら":{"zenkaku":"ラ","hankaku":"ﾗ"},
    "り":{"zenkaku":"リ","hankaku":"ﾘ"},
    "る":{"zenkaku":"ル","hankaku":"ﾙ"},
    "れ":{"zenkaku":"レ","hankaku":"ﾚ"},
    "ろ":{"zenkaku":"ロ","hankaku":"ﾛ"},
    "ゎ":{"zenkaku":"ヮ","hankaku":"ﾜ"},
    "わ":{"zenkaku":"ワ","hankaku":"ﾜ"},
    "ゐ":{"zenkaku":"ヰ","hankaku":"ｲ"},
    "ゑ":{"zenkaku":"ヱ","hankaku":"ｴ"},
    "を":{"zenkaku":"ヲ","hankaku":"ｦ"},
    "ん":{"zenkaku":"ン","hankaku":"ﾝ"},
    "ー":{"zenkaku":"ー","hankaku":"ｰ"}
  },
  roma2hiragana:[
    /**
     * replace -> ローマ字にmatchするかのチェックに使う
     * with -> replaceにmatchした文字列を置き換える(通常は文字列を削除することになるが、子音の重複を取り除くこと等がある)
     * roma -> 定義されている場合はローマ字の表記として扱われる。されていない場合はreplaceがmatchしたものがローマ字の表記として扱われる
     * hiragana -> かなの表記として扱われる
     */
    {"replace":/^t'yu/i,"with":"","hiragana":"てゅ"},
    {"replace":/^d'yu/i,"with":"","hiragana":"でゅ"},
    {"replace":/^hwyu/i,"with":"","hiragana":"ふゅ"},
    {"replace":/^[lx]tsu/i,"with":"","hiragana":"っ"},
    {"replace":/^shi/i,"with":"","hiragana":"し"},
    {"replace":/^chi/i,"with":"","hiragana":"ち"},
    {"replace":/^tsu/i,"with":"","hiragana":"つ"},
    {"replace":/^wyi/i,"with":"","hiragana":"ゐ"},
    {"replace":/^wye/i,"with":"","hiragana":"ゑ"},
    {"replace":/^kya/i,"with":"","hiragana":"きゃ"},
    {"replace":/^kyu/i,"with":"","hiragana":"きゅ"},
    {"replace":/^kyo/i,"with":"","hiragana":"きょ"},
    {"replace":/^gya/i,"with":"","hiragana":"ぎゃ"},
    {"replace":/^gyu/i,"with":"","hiragana":"ぎゅ"},
    {"replace":/^gyo/i,"with":"","hiragana":"ぎょ"},
    {"replace":/^sya/i,"with":"","hiragana":"しゃ"},
    {"replace":/^sha/i,"with":"","hiragana":"しゃ"},
    {"replace":/^syu/i,"with":"","hiragana":"しゅ"},
    {"replace":/^shu/i,"with":"","hiragana":"しゅ"},
    {"replace":/^syo/i,"with":"","hiragana":"しょ"},
    {"replace":/^sho/i,"with":"","hiragana":"しょ"},
    {"replace":/^zya/i,"with":"","hiragana":"じゃ"},
    {"replace":/^zyu/i,"with":"","hiragana":"じゅ"},
    {"replace":/^zyo/i,"with":"","hiragana":"じょ"},
    {"replace":/^tya/i,"with":"","hiragana":"ちゃ"},
    {"replace":/^cha/i,"with":"","hiragana":"ちゃ"},
    {"replace":/^tyu/i,"with":"","hiragana":"ちゅ"},
    {"replace":/^chu/i,"with":"","hiragana":"ちゅ"},
    {"replace":/^tyo/i,"with":"","hiragana":"ちょ"},
    {"replace":/^cho/i,"with":"","hiragana":"ちょ"},
    {"replace":/^dya/i,"with":"","hiragana":"ぢゃ"},
    {"replace":/^dyu/i,"with":"","hiragana":"ぢゅ"},
    {"replace":/^dyo/i,"with":"","hiragana":"ぢょ"},
    {"replace":/^nya/i,"with":"","hiragana":"にゃ"},
    {"replace":/^nyu/i,"with":"","hiragana":"にゅ"},
    {"replace":/^nyo/i,"with":"","hiragana":"にょ"},
    {"replace":/^hya/i,"with":"","hiragana":"ひゃ"},
    {"replace":/^hyu/i,"with":"","hiragana":"ひゅ"},
    {"replace":/^hyo/i,"with":"","hiragana":"ひょ"},
    {"replace":/^bya/i,"with":"","hiragana":"びゃ"},
    {"replace":/^byu/i,"with":"","hiragana":"びゅ"},
    {"replace":/^byo/i,"with":"","hiragana":"びょ"},
    {"replace":/^pya/i,"with":"","hiragana":"ぴゃ"},
    {"replace":/^pyu/i,"with":"","hiragana":"ぴゅ"},
    {"replace":/^pyo/i,"with":"","hiragana":"ぴょ"},
    {"replace":/^mya/i,"with":"","hiragana":"みゃ"},
    {"replace":/^myu/i,"with":"","hiragana":"みゅ"},
    {"replace":/^myo/i,"with":"","hiragana":"みょ"},
    {"replace":/^rya/i,"with":"","hiragana":"りゃ"},
    {"replace":/^ryu/i,"with":"","hiragana":"りゅ"},
    {"replace":/^ryo/i,"with":"","hiragana":"りょ"},
    {"replace":/^sye/i,"with":"","hiragana":"しぇ"},
    {"replace":/^she/i,"with":"","hiragana":"しぇ"},
    {"replace":/^zye/i,"with":"","hiragana":"じぇ"},
    {"replace":/^tye/i,"with":"","hiragana":"ちぇ"},
    {"replace":/^che/i,"with":"","hiragana":"ちぇ"},
    {"replace":/^tsa/i,"with":"","hiragana":"つぁ"},
    {"replace":/^tse/i,"with":"","hiragana":"つぇ"},
    {"replace":/^tso/i,"with":"","hiragana":"つぉ"},
    {"replace":/^thi/i,"with":"","hiragana":"てぃ"},
    {"replace":/^dhi/i,"with":"","hiragana":"でぃ"},
    {"replace":/^dhu/i,"with":"","hiragana":"でゅ"},
    {"replace":/^[lx]ka/i,"with":"","hiragana":"ヵ"},
    {"replace":/^[lx]ke/i,"with":"","hiragana":"ヶ"},
    {"replace":/^[lx]tu/i,"with":"","hiragana":"っ"},
    {"replace":/^[lx]ya/i,"with":"","hiragana":"ゃ"},
    {"replace":/^[lx]yu/i,"with":"","hiragana":"ゅ"},
    {"replace":/^[lx]yo/i,"with":"","hiragana":"ょ"},
    {"replace":/^[lx]wa/i,"with":"","hiragana":"ゎ"},
    {"replace":/^whi/i,"with":"","hiragana":"うぃ"},
    {"replace":/^whe/i,"with":"","hiragana":"うぇ"},
    {"replace":/^who/i,"with":"","hiragana":"うぉ"},
    {"replace":/^vyu/i,"with":"","hiragana":"ヴゅ"},	//ゔゅは変換サービスでエラーになるので変更	
    {"replace":/^kwa/i,"with":"","hiragana":"くぁ"},
    {"replace":/^kwi/i,"with":"","hiragana":"くぃ"},
    {"replace":/^kwe/i,"with":"","hiragana":"くぇ"},
    {"replace":/^kwo/i,"with":"","hiragana":"くぉ"},
    {"replace":/^gwa/i,"with":"","hiragana":"ぐぁ"},
    {"replace":/^jya/i,"with":"","hiragana":"じゃ"},
    {"replace":/^jyu/i,"with":"","hiragana":"じゅ"},
    {"replace":/^jyo/i,"with":"","hiragana":"じょ"},
    {"replace":/^cya/i,"with":"","hiragana":"ちゃ"},
    {"replace":/^cyu/i,"with":"","hiragana":"ちゅ"},
    {"replace":/^cyo/i,"with":"","hiragana":"ちょ"},
    {"replace":/^tsi/i,"with":"","hiragana":"つぃ"},
    {"replace":/^t'i/i,"with":"","hiragana":"てぃ"},
    {"replace":/^d'i/i,"with":"","hiragana":"でぃ"},
    {"replace":/^thu/i,"with":"","hiragana":"てゅ"},
    {"replace":/^twu/i,"with":"","hiragana":"とぅ"},
    {"replace":/^t'u/i,"with":"","hiragana":"とぅ"},
    {"replace":/^dwu/i,"with":"","hiragana":"どぅ"},
    {"replace":/^d'u/i,"with":"","hiragana":"どぅ"},
    {"replace":/^hwa/i,"with":"","hiragana":"ふぁ"},
    {"replace":/^hwi/i,"with":"","hiragana":"ふぃ"},
    {"replace":/^hwe/i,"with":"","hiragana":"ふぇ"},
    {"replace":/^hwo/i,"with":"","hiragana":"ふぉ"},
    {"replace":/^fyu/i,"with":"","hiragana":"ふゅ"},
    {"replace":/^b(b)/i,"with":"$1","roma":"b","hiragana":"っ"},
    {"replace":/^c(c)/i,"with":"$1","roma":"c","hiragana":"っ"},
    {"replace":/^d(d)/i,"with":"$1","roma":"d","hiragana":"っ"},
    {"replace":/^f(f)/i,"with":"$1","roma":"f","hiragana":"っ"},
    {"replace":/^g(g)/i,"with":"$1","roma":"q","hiragana":"っ"},
    {"replace":/^h(h)/i,"with":"$1","roma":"h","hiragana":"っ"},
    {"replace":/^j(j)/i,"with":"$1","roma":"j","hiragana":"っ"},
    {"replace":/^k(k)/i,"with":"$1","roma":"k","hiragana":"っ"},
    {"replace":/^l(l)/i,"with":"$1","roma":"l","hiragana":"っ"},
    {"replace":/^m(m)/i,"with":"$1","roma":"m","hiragana":"っ"},
    {"replace":/^p(p)/i,"with":"$1","roma":"p","hiragana":"っ"},
    {"replace":/^q(q)/i,"with":"$1","roma":"q","hiragana":"っ"},
    {"replace":/^r(r)/i,"with":"$1","roma":"r","hiragana":"っ"},
    {"replace":/^s(s)/i,"with":"$1","roma":"s","hiragana":"っ"},
    {"replace":/^t(t)/i,"with":"$1","roma":"t","hiragana":"っ"},
    {"replace":/^v(v)/i,"with":"$1","roma":"v","hiragana":"っ"},
    {"replace":/^w(w)/i,"with":"$1","roma":"w","hiragana":"っ"},
    {"replace":/^x(x)/i,"with":"$1","roma":"x","hiragana":"っ"},
    {"replace":/^y(y)/i,"with":"$1","roma":"y","hiragana":"っ"},
    {"replace":/^z(z)/i,"with":"$1","roma":"z","hiragana":"っ"},
    {"replace":/^ka/i,"with":"","hiragana":"か"},
    {"replace":/^ki/i,"with":"","hiragana":"き"},
    {"replace":/^ku/i,"with":"","hiragana":"く"},
    {"replace":/^ke/i,"with":"","hiragana":"け"},
    {"replace":/^ko/i,"with":"","hiragana":"こ"},
    {"replace":/^ga/i,"with":"","hiragana":"が"},
    {"replace":/^gi/i,"with":"","hiragana":"ぎ"},
    {"replace":/^gu/i,"with":"","hiragana":"ぐ"},
    {"replace":/^ge/i,"with":"","hiragana":"げ"},
    {"replace":/^go/i,"with":"","hiragana":"ご"},
    {"replace":/^sa/i,"with":"","hiragana":"さ"},
    {"replace":/^si/i,"with":"","hiragana":"し"},
    {"replace":/^su/i,"with":"","hiragana":"す"},
    {"replace":/^se/i,"with":"","hiragana":"せ"},
    {"replace":/^so/i,"with":"","hiragana":"そ"},
    {"replace":/^za/i,"with":"","hiragana":"ざ"},
    {"replace":/^zi/i,"with":"","hiragana":"じ"},
    {"replace":/^ji/i,"with":"","hiragana":"じ"},
    {"replace":/^zu/i,"with":"","hiragana":"ず"},
    {"replace":/^ze/i,"with":"","hiragana":"ぜ"},
    {"replace":/^zo/i,"with":"","hiragana":"ぞ"},
    {"replace":/^ta/i,"with":"","hiragana":"た"},
    {"replace":/^ti/i,"with":"","hiragana":"ち"},
    {"replace":/^tu/i,"with":"","hiragana":"つ"},
    {"replace":/^te/i,"with":"","hiragana":"て"},
    {"replace":/^to/i,"with":"","hiragana":"と"},
    {"replace":/^da/i,"with":"","hiragana":"だ"},
    {"replace":/^di/i,"with":"","hiragana":"ぢ"},
    {"replace":/^du/i,"with":"","hiragana":"づ"},
    {"replace":/^de/i,"with":"","hiragana":"で"},
    {"replace":/^do/i,"with":"","hiragana":"ど"},
    {"replace":/^na/i,"with":"","hiragana":"な"},
    {"replace":/^ni/i,"with":"","hiragana":"に"},
    {"replace":/^nu/i,"with":"","hiragana":"ぬ"},
    {"replace":/^ne/i,"with":"","hiragana":"ね"},
    {"replace":/^no/i,"with":"","hiragana":"の"},
    {"replace":/^ha/i,"with":"","hiragana":"は"},
    {"replace":/^hi/i,"with":"","hiragana":"ひ"},
    {"replace":/^hu/i,"with":"","hiragana":"ふ"},
    {"replace":/^fu/i,"with":"","hiragana":"ふ"},
    {"replace":/^he/i,"with":"","hiragana":"へ"},
    {"replace":/^ho/i,"with":"","hiragana":"ほ"},
    {"replace":/^ba/i,"with":"","hiragana":"ば"},
    {"replace":/^bi/i,"with":"","hiragana":"び"},
    {"replace":/^bu/i,"with":"","hiragana":"ぶ"},
    {"replace":/^be/i,"with":"","hiragana":"べ"},
    {"replace":/^bo/i,"with":"","hiragana":"ぼ"},
    {"replace":/^pa/i,"with":"","hiragana":"ぱ"},
    {"replace":/^pi/i,"with":"","hiragana":"ぴ"},
    {"replace":/^pu/i,"with":"","hiragana":"ぷ"},
    {"replace":/^pe/i,"with":"","hiragana":"ぺ"},
    {"replace":/^po/i,"with":"","hiragana":"ぽ"},
    {"replace":/^ma/i,"with":"","hiragana":"ま"},
    {"replace":/^mi/i,"with":"","hiragana":"み"},
    {"replace":/^mu/i,"with":"","hiragana":"む"},
    {"replace":/^me/i,"with":"","hiragana":"め"},
    {"replace":/^mo/i,"with":"","hiragana":"も"},
    {"replace":/^ya/i,"with":"","hiragana":"や"},
    {"replace":/^yu/i,"with":"","hiragana":"ゆ"},
    {"replace":/^yo/i,"with":"","hiragana":"よ"},
    {"replace":/^ra/i,"with":"","hiragana":"ら"},
    {"replace":/^ri/i,"with":"","hiragana":"り"},
    {"replace":/^ru/i,"with":"","hiragana":"る"},
    {"replace":/^re/i,"with":"","hiragana":"れ"},
    {"replace":/^ro/i,"with":"","hiragana":"ろ"},
    {"replace":/^wa/i,"with":"","hiragana":"わ"},
    {"replace":/^wo/i,"with":"","hiragana":"を"},
    {"replace":/^n'/i,"with":"","hiragana":"ん"},
    {"replace":/^nn/i,"with":"","hiragana":"ん"},
    {"replace":/^ja/i,"with":"","hiragana":"じゃ"},
    {"replace":/^ju/i,"with":"","hiragana":"じゅ"},
    {"replace":/^jo/i,"with":"","hiragana":"じょ"},
    {"replace":/^je/i,"with":"","hiragana":"じぇ"},
    {"replace":/^fa/i,"with":"","hiragana":"ふぁ"},
    {"replace":/^fi/i,"with":"","hiragana":"ふぃ"},
    {"replace":/^fe/i,"with":"","hiragana":"ふぇ"},
    {"replace":/^fo/i,"with":"","hiragana":"ふぉ"},
    {"replace":/^[lx]a/i,"with":"","hiragana":"ぁ"},
    {"replace":/^[lx]i/i,"with":"","hiragana":"ぃ"},
    {"replace":/^[lx]u/i,"with":"","hiragana":"ぅ"},
    {"replace":/^[lx]e/i,"with":"","hiragana":"ぇ"},
    {"replace":/^[lx]o/i,"with":"","hiragana":"ぉ"},
    {"replace":/^ye/i,"with":"","hiragana":"いぇ"},
    {"replace":/^wi/i,"with":"","hiragana":"うぃ"},
    {"replace":/^we/i,"with":"","hiragana":"うぇ"},
    {"replace":/^va/i,"with":"","hiragana":"ヴぁ"},	//ゔぁは変換サービスでエラーになるので変更
    {"replace":/^vi/i,"with":"","hiragana":"ヴぃ"},	//ゔぃは変換サービスでエラーになるので変更
    {"replace":/^vu/i,"with":"","hiragana":"ヴ"},	//ゔは変換サービスでエラーになるので変更
    {"replace":/^ve/i,"with":"","hiragana":"ヴぇ"},	//ゔぇは変換サービスでエラーになるので変更
    {"replace":/^vo/i,"with":"","hiragana":"ヴぉ"},	//ゔぉは変換サービスでエラーになるので変更
    {"replace":/^qa/i,"with":"","hiragana":"くぁ"},
    {"replace":/^qi/i,"with":"","hiragana":"くぃ"},
    {"replace":/^qe/i,"with":"","hiragana":"くぇ"},
    {"replace":/^qo/i,"with":"","hiragana":"くぉ"},
    {"replace":/^a/i,"with":"","hiragana":"あ"},
    {"replace":/^i/i,"with":"","hiragana":"い"},
    {"replace":/^u/i,"with":"","hiragana":"う"},
    {"replace":/^e/i,"with":"","hiragana":"え"},
    {"replace":/^o/i,"with":"","hiragana":"お"},
    {"replace":/^-/i,"with":"","hiragana":"ー"},
    //{"replace"^:/\^/i,"with":"","hiragana":"ー"}	//あまり一般的でなさそうなので除外
    {"replace":/^n([^aiueoy])/i,"with":"$1","roma":"n","hiragana":"ん"},	//末尾の一文字がnのときにはヒットさせない。それについては変換時に例外処理をいれる。
    {"replace":/^,/i,"with":"","hiragana":"、"},	//以下、追加した方がいいリストにも無かったが、あったほうが便利なので
    {"replace":/^\./i,"with":"","hiragana":"。"},
    {"replace":/^\[/i,"with":"","hiragana":"「"},
    {"replace":/\]/i,"with":"","hiragana":"」"},
    {"replace":/\//i,"with":"","hiragana":"・"}
  ]
};
var roma2hiragana_tbl = chr_convtbl.roma2hiragana;
var roma2hiragana_tbl_len = chr_convtbl.roma2hiragana.length;
var hankaku2zenkaku = chr_convtbl.hankaku2zenkaku;

if(typeof(require) != 'undefined' &&
   typeof(module) != 'undefined' &&
   typeof(module.exports) != 'undefined' &&
   typeof(exports) != 'undefined') {
    exports.conv = conv;
}else{
  window.Roman2Hiragana = {
    conv: conv
  };
}

})();
